### ISSUE TITLE
Error: Parameter "parentChannel" needs to be of type "string" but type "undefined" has been passed

### ISSUE THREAD

**Issue by Vetinari1977** [phillipssc/ioBroker.rtl_433#23]
System:
Raspi 4
Software : IObroker
Node-Js Version: v16.18.0
NPM Version: 8.19.2

Problem:
When new Nexus TH sensors (Bresser tempreture sensors) will be registered, then only the Info and Meta folders will be created and no sensor datas like tempreture and so on are avaylable. In the protokoll of the IOBroker the message from the headline is prompted. All existing sensors works well. Maybe it has started after an update to a newer Js or NPM version, but not sure because it's long ago after I've inserted a new sensor.

**Comment by Vogtlaender** [comment]
Error: Parameter "parentChannel" needs to be of type "string" but type "undefined" has been passed

Hello, I currently have exactly the same problem after I updated to the current Js or NPM version.
Is there already a solution?

**Comment by phillipssc** [comment]
This should be fixed in the latest code checked into git.  Will publish to npm shortly

**Comment by randomname32** [comment]
I have the same problem. I just tried the latest version from npm (1.1.6), but the issue is still the same. Do I have to restart/reboot anything before testing the updated version?

Version 1.1.6 in /opt/iobroker/node_modules/iobroker.rtl_433, node: v18.18.2, js-controller: 5.0.17

**Comment by randomname32** [comment]
I'm sorry, while I was writing the previous comment, the values for temperature and humidity arrived.
-> version 1.1.6 solves the issue
Thanks a lot!
